name: Date Check
on: 
  schedule: 
      - cron: '40 6 * * 1-5'

env:
  creds: ${{ secrets.creds }}
  spreadsheet_id: ${{ secrets.spreadsheet_id }}
  bot_token: ${{ secrets.bot_token }}
  channel_id: ${{ secrets.channel_id }}
  host: ${{ secrets.host }}
  ch_username: ${{ secrets.ch_username }}
  password: ${{ secrets.password }}
  database: ${{ secrets.database }}
  range_names: ${{ secrets.range_names }}


jobs:
    Date-Check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dependecies
              run: pip install -r requirements.txt
            - name: Get Certificate
              run: sudo mkdir --parents /usr/local/share/ca-certificates/Yandex/ &&  sudo wget "https://storage.yandexcloud.net/cloud-certs/RootCA.pem" --output-document /usr/local/share/ca-certificates/Yandex/RootCA.crt && sudo wget "https://storage.yandexcloud.net/cloud-certs/IntermediateCA.pem"  --output-document /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt && sudo chmod 655 /usr/local/share/ca-certificates/Yandex/RootCA.crt /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt && sudo update-ca-certificates
            - name: Run Date Check
              run: python date_check.py
