name: Date Check
on: [push]

env:
  host: ${{ secrets.host }}
  ch_username: ${{ secrets.ch_username }}
  password: ${{ secrets.password }}
  client_cert: ${{ secrets.client_cert }}
  creds: ${{ secrets.creds }}
  spreadsheet_id: ${{ secrets.spreadsheet_id }}
  date_range_name: ${{ secrets.date_range_name }}
  month_range_name: ${{ secrets.month_range_name }}
  bot_token: ${{ secrets.bot_token }}
  channel_id: ${{ secrets.channel_id }}

jobs:
    Date-Check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dependecies
              run: pip install -r requirements.txt
            - name: Run Date Check
              run: date_check.py
